model:
  arch: resnet18_mixer
  pretrained: False
  emb_dim: 512
  maxpool: 1
  out_activation: linear
  activation: relu
  mixer:
    num_layers: 2
    num_heads: 4
    dropout: 0.1
    loss_weight: 1.0
    detach_target: False
    use_classifier: False

training:
  optimizer:
    lr: 0.001

data:
  training:
    batch_size: 256
  testing:
    batch_size: 2048
