data:
  training:
    dataset: clevr
    path: data/CLEVR
    targets:
    split_attributes:
    split: composition
    split_difficulty: 0.1
    train: True
    shuffle: True
    batch_size: 1024
    downsample: 0
    val_fraction: 0.1
    num_workers: 1
    non_iid:
      name: non_iid
      apply_to: ["training", "validation"]
    attributes: &ATT
      - name: shape
        out_dim: 3
        var: 1
      - name: size
        out_dim: 3
        var: 0.2
      - name: material
        out_dim: 2
        var: 1
      - name: color
        out_dim: 8
        var: 1
  testing:
    dataset: ${data.training.dataset}
    path: ${data.training.path}
    targets: ${data.training.targets}
    split_attributes: ${data.training.split_attributes}
    split: ${data.training.split}
    split_difficulty: ${data.training.split_difficulty}
    train: False
    shuffle: False
    batch_size: 2048
    downsample: 0
    num_workers: 1
    attributes: *ATT

training:
  n_epoch: 250

model:
  preprocessing:
    - arch: augmentator
      train:
        - name: resize
          size: 128
          antialias: True
      test:
        - name: resize
          size: 128
          antialias: True

  feature_extraction:
    in_channels: 3
