data:
  training:
    dataset: dsprites
    path: data/dsprites/dsprites.npz
    targets:
    split_attributes:
    split: composition
    split_difficulty: 0.1
    train: True
    shuffle: True
    batch_size: 1024
    downsample: 0
    val_fraction: 0.1
    num_workers: 1
    non_iid:
      name: non_iid
      apply_to: ["training", "validation"]
    attributes: &ATT
      - name: shape
        out_dim: 3
        var: 1.0
      - name: scale
        out_dim: 6
        var: 0.2
      - name: orientation
        out_dim: 40
        var: 0.2
      - name: x-position
        out_dim: 32
        var: 0.2
      - name: y-position
        out_dim: 32
        var: 0.2
  testing:
    dataset: ${data.training.dataset}
    path: ${data.training.path}
    targets: ${data.training.targets}
    split_attributes: ${data.training.split_attributes}
    split: ${data.training.split}
    split_difficulty: ${data.training.split_difficulty}
    train: False
    shuffle: False
    batch_size: 2048
    downsample: 0
    num_workers: 1
    attributes: *ATT

model:

  preprocessing:
    - arch: augmentator
      train:
        - name: resize
          size: 64
          antialias: True
        - name: gauss_blur
          kernel_size: [23, 23]
          sigma: [0.1, 0.3]
      test:
        - name: resize
          size: 64
          antialias: True
        - name: gauss_blur
          kernel_size: [23, 23]
          sigma: [0.1, 0.3]

  feature_extraction:
    in_channels: 1
