data:
  training:
    dataset: iraven
    path: data/I-RAVEN
    dataset_subset: C
    targets:
    split_attributes:
    split: composition
    split_difficulty: 1
    max_objects: 1
    train: True
    shuffle: True
    batch_size: 1024
    downsample: 0
    val_fraction: 0.1
    num_workers: 1
    non_iid:
      name: non_iid
      apply_to: ["training", "validation"]
    attributes: &ATT
      - name: position
        out_dim: ${num_pos:${data.training.dataset_subset}}
        var: 0.2
      - name: angle
        out_dim: 8
        var: 0.2
      - name: color
        out_dim: 10
        var: 0.2
      - name: size
        out_dim: 6
        var: 0.2
      - name: type
        out_dim: 5
        var: 1
  testing:
    dataset: ${data.training.dataset}
    path: ${data.training.path}
    dataset_subset: ${data.training.dataset_subset}
    targets: ${data.training.targets}
    split_attributes: ${data.training.split_attributes}
    split: ${data.training.split}
    split_difficulty: ${data.training.split_difficulty}
    max_objects: ${data.training.max_objects}
    train: False
    shuffle: False
    batch_size: 2048
    downsample: 0
    num_workers: 1
    attributes: *ATT

model:

  preprocessing:
    - arch: augmentator
      train:
        - name: resize
          size: 64
          antialias: True
        - name: padding
          padding: 5
          fill: 0
        - name: rand_crop
          size: 64
          fill: 0
        - name: rand_rotation
          degrees: 360
          fill: 0
        - name: gauss_blur
          kernel_size: [41, 41]
          sigma: [0.1, 0.3]
      test:
        - name: resize
          size: 64
          antialias: True
        - name: rand_rotation
          degrees: 360
          fill: 0
        - name: gauss_blur
          kernel_size: [41, 41]
          sigma: [0.1, 0.3]

  feature_extraction:
    in_channels: 1
