data:
  training:
    dataset: shapes3d
    path: data/shapes3d/3dshapes.h5
    targets:
    split_attributes:
    split: interpolation
    split_difficulty: 1
    train: True
    shuffle: True
    batch_size: 1024
    downsample: 0
    val_fraction: 0.1
    num_workers: 1
    non_iid:
      name: non_iid
      apply_to: ["training", "validation"]
    attributes: &ATT
      - name: floor
        out_dim: 10
        var: 0.2
      - name: wall
        out_dim: 10
        var: 0.2
      - name: object
        out_dim: 10
        var: 0.2
      - name: scale
        out_dim: 8
        var: 0.2
      - name: shape
        out_dim: 4
        var: 0.2
      - name: orientation
        out_dim: 15
        var: 0.2
  testing:
    dataset: ${data.training.dataset}
    path: ${data.training.path}
    targets: ${data.training.targets}
    split_attributes: ${data.training.split_attributes}
    split: ${data.training.split}
    split_difficulty: ${data.training.split_difficulty}
    train: False
    shuffle: False
    batch_size: 2048
    downsample: 0
    num_workers: 1
    attributes: *ATT

model:

  preprocessing:
    - arch: augmentator
      train:
        - name: resize
          size: 64
          antialias: True
        - name: gauss_blur
          kernel_size: [ 23, 23 ]
          sigma: 0.2
      test:
        - name: resize
          size: 64
          antialias: True
        - name: gauss_blur
          kernel_size: [ 23, 23 ]
          sigma: 0.2

  feature_extraction:
    in_channels: 3
